import { Footer } from "@/components/Footer";
import { Navbar } from "@/components/Navbar";
import { getAllPaths } from "@/hooks/getAllPaths";
import { getPageData } from "@/hooks/getPageData";
import { PageType } from "@/utils/baseTypes";
import { Modules } from "@/utils/module-list";
import { GetStaticPropsContext } from "next";

import Head from "next/head";

interface DynamicPageProps {
  pageData: PageType[];
}

export default function DynamicPage({ pageData }: DynamicPageProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        {pageData[0] &&
          pageData[0].attributes.Module &&
          pageData[0].attributes.Module.map((module, index) => (
            <Modules key={index} module={module} />
          ))}
        <Footer data={true} />
      </main>
    </>
  );
}

export async function getStaticPaths({}) {
  const allPaths = await getAllPaths();
  return {
    paths: allPaths,
    fallback: "blocking",
  };
}

export async function getStaticProps(context: GetStaticPropsContext) {
  const { dynamicRoute }: any = context.params;

  const pageData = await getPageData(dynamicRoute);

  return {
    props: {
      pageData,
    },
    revalidate: 120,
  };
}
